### ISSUE TITLE
tput error: no value for $TERM and no -T specified

### ISSUE THREAD

**Issue by mattez** [jimeh/git-aware-prompt#19]
I'm getting error when loging to Ubuntu 14.04 LTS. I suspect git-aware-prompt. could it be?
![login error screenshot](https://cloud.githubusercontent.com/assets/143115/6617328/f48b0726-c8b7-11e4-954e-848345bbc142.jpg)

Im not a progamator, but I was searching and I found this. It can not be a solution? Testing for an interactive shell?

```
# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
    # Shell is non-interactive.  Be done now!
    return
fi
```

**Comment by srvanrell** [comment]
I had the same problem recently.
Comment out the lines regarding git-aware-prompt in .profile and add
them to your .bash_profile.
I think this problem was raised after an update.
Hope that help you!

2015-03-12 9:09 GMT-03:00, Matěj Kříž <notifications@github.com>:
> im getting error when login to ubuntu. I suspect git-aware-prompt. could it
> be?
> ![login error
> screenshot](https://cloud.githubusercontent.com/assets/143115/6617328/f48b0726-c8b7-11e4-954e-848345bbc142.jpg)
>
> Im not a progamator, but I was searching and I found this. It can not be a
> solution? Testing for an interactive shell?
>
> ```
> # Test for an interactive shell.  There is no need to set anything
> # past this point for scp and rcp, and it's important to refrain from
> # outputting anything in those cases.
> if [[ $- != *i* ]] ; then
>     # Shell is non-interactive.  Be done now!
>     return
> fi
> ```
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jimeh/git-aware-prompt/issues/19


-- 
Sebastián

**Comment by jimeh** [comment]
Hmm, it does look like it's due to git-aware-prompt's use of the `tput` command. I'll look into a solution.

In the meantime, either try @srvanrell's solution of putting the git-aware-prompt related stuff in `~/.bash_profile` instead of `~/.profile`. Or if that doesn't work, try replacing it with something like this:

```bash
if [ -n $TERM ]; then
  export GITAWAREPROMPT=~/.bash/git-aware-prompt
  source $GITAWAREPROMPT/main.sh
  export PS1="\u@\h \w \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "
fi
```

**Comment by mattez** [comment]
@srvanrell's solution WORKs fine. Great. Thank you @srvanrell. Thank you @jimeh.

**Comment by srvanrell** [comment]
Glad to hear that!

By the way, I'm using Ubuntu (14.04) too

Sebastián

**Comment by mattez** [comment]
I forgot to mention it: YES I'm using **Ubuntu 14.04 LTS**
@srvanrell: (I don't know how you can know it :)

**Comment by srvanrell** [comment]
@mattez (just a guess by what you post in your first message)

**Comment by jimeh** [comment]
This will hopefully be avoided in the future thanks to da05b8dbb8325a4be669686e2edc09602d08d58a and some re-wording of the readme.
