### ISSUE TITLE
Getting some weird prompts.

### ISSUE THREAD

**Issue by sinkingshriek** [jimeh/git-aware-prompt#20]
Hey guys,
Not sure if this is just me but can anyone confirm if it's working for them or it's just me?
I'm using `Ubuntu 14.10` and it was working fine but it just stopped working one day. I don't know what I did.
I have cloned `git-aware-promp` in `.bash` directory. The following lines of codes are at the end of my`.bashrc` file

```
export GITAWAREPROMPT=~/.bash/git-aware-prompt
source $GITAWAREPROMPT/main.sh
export PS1="\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]@\h\[\033[00m\]:\[\033[01;34m\]t_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ ""]]]"
```
but I get this:-
![weird-prompt](https://cloud.githubusercontent.com/assets/682197/7245553/b2b48e98-e7b2-11e4-95c1-36386b135c8f.png)
That's the prompt I get without even typing anything. 
I'm not super good at changing prompt shells. :cry:

**Comment by jimeh** [comment]
Hey, I believe it's you. You've got a couple of typos in your PS1 line :) 

Try changing it to this:

```bash
export PS1="\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]@\h\[\033[00m\]:\[\033[01;34m\]$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "
```

Or if you want to include your username and current directory in the prompt, here's the suggested colorized PS1 line from the readme:

```bash
export PS1="\${debian_chroot:+(\$debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "
```

**Comment by sinkingshriek** [comment]
I see what's going on. For some reason when I paste in `vim` it's adding this `"]]]"` extra characters. I know I had copied and pasted the `PS1` from the `readme` file. 
Thanks for confirming @jimeh :smiley:
