### ISSUE TITLE
getting long bash prompt with whole dir hierarchy

### ISSUE THREAD

**Issue by link2pk** [jimeh/git-aware-prompt#28]
Hi Jimeh,

your plugin is great & it is working but I'm getting the whole directory structure in bash prompt like:
mac-user-name: /Applications/XAMPP/htdocs/projectname (branch-name) $

Can I just have the branch-name like:
mac-user-name:projectname (branch-name) $

I'm on OSX El Capitan.
Thanks & thank you for this plugin

**Comment by jimeh** [comment]
Hey, you can get back to full default OSX prompt style by setting PS1 like so:

```bash
export PS1="\u@\h \W \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\$ "
```

The difference from the OSX variant in the readme is the use of `\W` instead of `\w`. I'll update the readme to use `\W` as that is now the default behavior of OSX as of quite a few years back.

**Comment by link2pk** [comment]
Great, working fine. 

Thanks a lot.
