### ISSUE TITLE
Prompt shows wrong branch

### ISSUE THREAD

**Issue by samtstern** [jimeh/git-aware-prompt#55]
Here's my configuration:
```
export PS1="\u@\h \W \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]\n\$ "
```

Right now in my terminal I see the following prompt:

```
samstern@samstern-macbookpro firebase-tools (master)
$
```

But when I run `git branch` you can see I am not on `master`:

samstern@samstern-macbookpro firebase-tools (master)

```
$ git branch
  fix-firestore-delete-escaping
  master
* ss-firestore-delete-bugfix
```

Any idea what's going on here?

**Comment by lethosor** [comment]
Have you also set PROMPT_COMMAND?

**Comment by samtstern** [comment]
No I don't have that set anywhere.

**Comment by lethosor** [comment]
https://github.com/jimeh/git-aware-prompt/blob/75781b7b7d825f09ed1a9b0eccb2b508da210f49/prompt.sh#L23
You should either source prompt.sh or add that line elsewhere. Without that, git_branch and git_dirty will probably only ever be set once.

**Comment by samtstern** [comment]
@lethosor that seemed to work, thanks!
