### ISSUE TITLE
Underline in all elements

### ISSUE THREAD

**Issue by jkeilla** [jimeh/git-aware-prompt#63]
When the underline style is apply in one element, for example, in path of the files, All the others elements too stay with underline style. 
My  personalization: `export PS1="\n \[$undblu\]\w \[$txtylw\]\$git_branch\[$txtred\]\$git_dirty\[$bldblu\] \$ \[$txtrst\]"`

Result:
![bash](https://user-images.githubusercontent.com/34096097/48638454-75d14e00-e9af-11e8-9066-0fa80e5d97ea.png)

I wear Ubuntu 16.04 with native bash

**Comment by lethosor** [comment]
That's how escape sequences work - it's not specific to this tool at all. `tput rmul` is what you need to clear the underline, so you can either add `$(tput rmul)` at the appropriate point in your prompt or to a variable in colors.sh.

**Comment by jkeilla** [comment]
You helped me, thank you :)
